# Generated by Django 5.0.2 on 2024-02-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Type',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
