# Generated by Django 5.0.3 on 2024-03-24 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webhook', '0011_alter_webhook_api_key'),
        ('api', '0002_order_webhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='webhook',
            field=models.ForeignKey(blank=True, limit_choices_to={'Management': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='api.managementprofile')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Webhook.webhook'),
        ),
    ]
