# Generated by Django 5.0.2 on 2024-03-09 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerProfile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='managementprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'MANAGEMENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementProfile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'RIDER'}, on_delete=django.db.models.deletion.CASCADE, related_name='RiderProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
