# Generated by Django 5.0.3 on 2024-03-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webhook', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='api_key',
            field=models.CharField(default='N8URJLte8YpzReMbsHz3veW5b2EVJuikZBr5gflKPCRYKNZaNea7yDgzRcUs1zy9', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='secret_key',
            field=models.CharField(default='p6r1cTa3HUUOwniE1iOIYe7JjNitW3H2SpKTe5zfwABaEGaPwsVvZf5scY2eXhye', max_length=64, unique=True),
        ),
    ]
