# Generated by Django 5.0.3 on 2024-03-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webhook', '0003_alter_webhook_api_key_alter_webhook_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='api_key',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='secret_key',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
