# Generated by Django 5.0.3 on 2024-03-22 15:24

import Webhook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webhook', '0004_alter_webhook_api_key_alter_webhook_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='api_key',
            field=models.CharField(blank=True, default=Webhook.models.unique_key, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='secret_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
