# Generated by Django 5.0.3 on 2024-03-22 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webhook', '0006_alter_webhook_api_key_alter_webhook_secret_key'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='Management',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Webhook', to='api.managementprofile'),
        ),
    ]
