# Generated by Django 5.0.3 on 2024-03-22 16:54

import Webhook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webhook', '0008_alter_webhook_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='api_key',
            field=models.CharField(default=Webhook.models.unique_key, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='secret_key',
            field=models.CharField(default=Webhook.models.unique_key, editable=False, max_length=64, unique=True),
        ),
    ]
