# Generated by Django 5.0.3 on 2024-03-24 05:18

import Webhook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webhook', '0010_webhook_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='api_key',
            field=models.CharField(default=Webhook.models.generate_api_key, editable=False, max_length=64, unique=True),
        ),
    ]
